version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_university
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streaming_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /Users/evailcenko/baumanka/db/labs/IU7_DB/lab_05/json:/tmp
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y postgresql-plpython3-18 &&
        docker-entrypoint.sh postgres
      "

volumes:
  postgres_data:
